
// Euler Project Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.


let fibNum = 0
let hold = 1
let hold2 = 1
let sum = 0

while(hold2 <= 4000000){

    fibNum = hold + hold2

    if(fibNum % 2 === 0){
        sum += fibNum
    }

    hold = hold2
    hold2 = fibNum
}

console.log("The sum of even valued terms of a Fibonaci sequence not exceeding four million is: " + sum)



